// general
export const ACTION_WAITER_START = "startWaiter";
export const ACTION_WAITER_END = "endWaiter";
export const ACTION_HANDLE_ERROR = "handleError";

// auth
export const ACTION_LOGIN = "ACTION_LOGIN";
export const ACTION_LOGOUT = "ACTION_LOGOUT";
export const ACTION_AUTHORIZE = "ACTION_AUTHORIZE";
export const ACTION_REGISTER = "ACTION_REGISTER";

// product
export const ACTION_GET_PRODUCT_IMAGE = "ACTION_GET_PRODUCT_IMAGE";
export const ACTION_GET_PRODUCT_IMAGES = "ACTION_GET_PRODUCT_IMAGES";
export const ACTION_CREATE_NEW_PRODUCT_IMAGE = "CREATE_NEW_PRODUCT_IMAGE";
export const ACTION_SAVE_PRODUCT_IMAGE = "ACTION_SAVE_PRODUCT_IMAGE";
