// auth
export const MUTATION_LOGIN = "MUTATION_LOGIN";
export const MUTATION_LOGOUT = "MUTATION_LOGOUT";

// admin
export const MUTATION_SET_PRODUCT_IMAGE = "MUTATION_SET_PRODUCT_IMAGE";
export const MUTATION_SET_PRODUCT_IMAGE_FIELD =
  "MUTATION_SET_PRODUCT_IMAGE_FIELD";
export const MUTATION_SET_PRODUCT_IMAGES = "MUTATION_SET_PRODUCT_IMAGES";
export const MUTATION_DELETE_PRODUCT_IMAGE = "MUTATION_DELETE_PRODUCT_IMAGE";
