export const WAITER_ADD_PRODUCT = "WAITER_ADD_PRODUCT";
export const WAITER_GET_PRODUCT = "WAITER_GET_PRODUCT";
export const WAITER_GET_PRODUCTS = "WAITER_GET_PRODUCTS";
export const WAITER_REMOVE_PRODUCT = "WAITER_REMOVE_PRODUCT";
