// auth
export const WAITER_LOGIN = "WAITER_LOGIN";
export const WAITER_LOGOUT = "WAITER_LOGOUT";
export const WAITER_AUTHORIZE = "WAITER_AUTHORIZE";
export const WAITER_REGISTER = "WAITER_REGISTER";

// admin
export const WAITER_UPDATE_PRODUCT = "WAITER_UPDATE_PRODUCT";
export const WAITER_GET_PRODUCTS = "WAITER_GET_PRODUCTS";
export const WAITER_REMOVE_PRODUCT = "WAITER_REMOVE_PRODUCT";
export const WAITER_ADD_PRODUCT = "WAITER_ADD_PRODUCT";
export const WAITER_GET_PRODUCT = "WAITER_GET_PRODUCT";
export const WAITER_GET_PRODUCT_IMAGE = "WAITER_GET_PRODUCT_IMAGE";
export const WAITER_GET_PRODUCT_IMAGES = "WAITER_GET_PRODUCT_IMAGES";
export const WAITER_SAVE_PRODUCT_IMAGE = "WAITER_SAVE_PRODUCT_IMAGE";
export const WAITER_DELETE_PRODUCT_IMAGE = "WAITER_DELETE_PRODUCT_IMAGE";
